### ISSUE TITLE
GPMLs that break json-svg conversion

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/wikipathways-database#12]
Just to keep track of the remaining "problem children" from the recent sync of all approved pathways, here's a list  pathways that can't be converted to pvjson, svg and png using our main script. I debugged quite a few, but these remain error-prone and I have no idea what to do about them. So, I'm ignore them for now :)

WP435
WP466
WP983
WP2371
WP3197
WP5287
WP590

**Comment by Chris-Evelo** [comment]
I quickly checked WP91 and the only special thing I saw is the "^" character in some of the compound names. Could that reason? For WP435 Tyms seems to have two anchors. I don't expect that to be the problem, but it is probably wrong anyway.

**Comment by AlexanderPico** [comment]
Manually uploaded old PNG and SVG to wp-assets and wp.gh.io/assets/img for these cases:

WP435
WP466
WP983
WP2371
WP3197
WP5287

**Comment by AlexanderPico** [comment]
Error for a new problematic GPML [WP5271](https://classic.wikipathways.org/index.php/Pathway:WP5271)

```
generating JSON and SVG files for WP5271
WP5271
/home/runner/work/wikipathways-database/wikipathways-database/wikipathways-database/pathways/WP5271/WP5271.gpml
/home/runner/work/wikipathways-database/wikipathways-database/wikipathways-assets/pathways/WP5271/WP5271.svg
WP5271
/home/runner/work/wikipathways-database/wikipathways-database/wikipathways-database/pathways/WP5271/WP5271.gpml
/home/runner/work/wikipathways-database/wikipathways-database/wikipathways-assets/pathways/WP5271/WP5271.json

/home/runner/work/wikipathways-database/wikipathways-database/wikipathways-database/scripts/generate-svgs/node_modules/bridgedb/src/spinoffs/TSVGetter.ts:96
        throw new VError(err, callString);
              ^
VError: in TSVGetter.get(
	url=https://webservice.bridgedb.org/Caulobacter vibrioides/xrefsBatch,
	method=POST,
	body=LMSP01020002	LIPID MAPS
A0A0H3C6D9	Uniprot-TrEMBL
LMFA01010001	LIPID MAPS
LMFA07050000	LIPID MAPS
LMSP02020000	LIPID MAPS
17115	ChEBI
LMSP02080000	LIPID MAPS
LMFA07050360	LIPID MAPS
A0A0H3C7E9	Uniprot-TrEMBL
A0A0H3C8X0	Uniprot-TrEMBL
A0A0H3C8X7	Uniprot-TrEMBL
15346	ChEBI
29863195	PubMed
34969973	PubMed
70360	Rhea
14762	Rhea
70528	Rhea
) with httpOptions={
  "timeout": 4000,
  "retryLimit": 2,
  "retryDelay": 3000
}
       tsvOptions={
  "headers": false,
  "objectMode": true,
  "delimiter": "\t",
  "comment": "#"
}: ajax error 500 in Rx.Observable.prototype.throughNodeStream
    at CatchSubscriber.selector (/home/runner/work/wikipathways-database/wikipathways-database/wikipathways-database/scripts/generate-svgs/node_modules/bridgedb/src/spinoffs/TSVGetter.ts:96:15)
    at CatchSubscriber.error (/home/runner/work/wikipathways-database/wikipathways-database/wikipathways-database/scripts/generate-svgs/node_modules/src/operators/catchError.ts:106:23)
    at MapSubscriber.Subscriber._error (/home/runner/work/wikipathways-database/wikipathways-database/wikipathways-database/scripts/generate-svgs/node_modules/src/Subscriber.ts:143:22)
    at MapSubscriber.Subscriber.error (/home/runner/work/wikipathways-database/wikipathways-database/wikipathways-database/scripts/generate-svgs/node_modules/src/Subscriber.ts:113:12)
    at AjaxSubscriber.Subscriber._error (/home/runner/work/wikipathways-database/wikipathways-database/wikipathways-database/scripts/generate-svgs/node_modules/src/Subscriber.ts:143:22)
    at AjaxSubscriber.Subscriber.error (/home/runner/work/wikipathways-database/wikipathways-database/wikipathways-database/scripts/generate-svgs/node_modules/src/Subscriber.ts:113:12)
    at XMLHttpRequest.xhrReadyStateChange [as onreadystatechange] (/home/runner/work/wikipathways-database/wikipathways-database/wikipathways-database/scripts/generate-svgs/node_modules/src/observable/dom/AjaxObservable.ts:378:22)
    at XMLHttpRequest.dispatchEvent (/home/runner/work/wikipathways-database/wikipathways-database/wikipathways-database/scripts/generate-svgs/node_modules/xhr2/lib/xhr2.js:76:20)
    at XMLHttpRequest._setReadyState (/home/runner/work/wikipathways-database/wikipathways-database/wikipathways-database/scripts/generate-svgs/node_modules/xhr2/lib/xhr2.js:422:14)
    at XMLHttpRequest._onHttpResponseEnd (/home/runner/work/wikipathways-database/wikipathways-database/wikipathways-database/scripts/generate-svgs/node_modules/xhr2/lib/xhr2.js:616:14)
gpmlconverter: Unknown Error
An error occurred in line 208 of file /home/runner/work/wikipathways-database/wikipathways-database/wikipathways-database/scripts/generate-svgs/gpmlconverter:
    bridgedb xrefs -f json \
gpmlconverter: Unknown Error
An error occurred in line 240 of file ./gpmlconverter:
  "$SCRIPT_DIR/gpmlconverter" --id "$ID" --pathway-version "$PATHWAY_VERSION" -i "$path_in" -o "$json_f"
Error: Process completed with exit code 1.
```

**Comment by AlexanderPico** [comment]
@hasanbalci This ticket has a short list of GPMLs that break the json-svg step. While you're looking into fixes to include in the next release of pvjson, you might want to run each of these and see if you have any ideas.

**Comment by hasanbalci** [comment]
I had a chance to check what the problems are with these pathway files and here are my initial observations:

WP435: I think this enters into an infinite loop somewhere during the generation of svg (in pvjs repo), because it gives memory error after some time.

WP466, WP983 and WP3197: It seems there are some arcs and/or nodes in these pathways that pvjs repo doesn't like while trying to generate the corresponding svg images. I identified some of them and if I remove those graph elements temporarily, svgs are generated but this time svg-to-png conversion gives error and cannot generate png images.

WP2371 and WP5287: It seems that svgs are generated but svg-to-png conversion gives error.

**Comment by hasanbalci** [comment]
WP590 also enters into infinite loop like WP435 while generating svg.

**Comment by egonw** [comment]
@hasanbalci, WP466 still breaks the SVG generation.

**Comment by hasanbalci** [comment]
Some possible fixes for the following four files:
- WP466 and WP983: The problem is on the curved edges below, pvjs cannot process them. Changing their style from curved to straight fixes the issue.

<img width="366" alt="Image" src="https://github.com/user-attachments/assets/37b704f2-7cb7-47b5-bd27-312587793974" />
 
WP3197: Change Line 1379 - RelX="0.9210526315789473" -> RelX="1.0". This doesn't affect the the appearance of the edge but fixes svg generation.

WP435: Line 539 - Remove LineStyle="Broken". This is a very short edge with only arrowhead is visible. Removing "Broken" line style doesn't affect the appearance of the edge but fixes svg conversion.

Others:
WP590: I think this has a similar problem with WP435, but when I fixed it and try to generate svg, I lose some edges.
WP2371 and WP5287: It seems that svgs are generated but svg-to-png conversion gives error and cannot generate png images.

@AlexanderPico If you are ok with the suggested changes for the four diagram above (WP466, WP983, WP3197 and WP435), I can apply changes. I will look further for the other three diagrams (WP590, WP2371 and WP5287).
